version: '2'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - //var/run/docker.sock:/tmp/docker.sock:ro

networks:
  default:
      external: true
      name: local-apps-network
  local-apps:
    name: local-apps-network
    driver: bridge
